# Generated by Django 2.2.28 on 2023-10-30 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 19, 25, 45, 906710), verbose_name='addtime'),
        ),
    ]
